# 应用主端口（对于非web应用，此配置不起作用，但保留是好习惯）
server:
  port: 8081

# Spring 应用配置
spring:
  application:
    name: Yiyan-Desktop
  main:
    banner-mode: "off" # 关闭启动时的 Banner
# 调度器配置
scheduler:
  min-delay-seconds: 10 # 最小随机延迟（秒）
  max-delay-seconds: 30 # 最大随机延迟（秒）

# 日志配置
logging:
  level:
    # 设置根日志级别为 info
    root: info
    # 您可以为特定的包设置不同的级别，例如：
    # com.yiyan: debug
  pattern:
    # 控制台输出格式
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    # 文件输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
  file:
    # 日志文件路径和名称
    name: logs/app.log
    # 保留归档日志文件的最大数量
    max-history: 30
    #单个日志文件的最大大小，默认为10MB
    max-size: 10MB

# 一言 API 端点配置
yiyan:
  default-user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
  max-text-length: 60 # "一言"文本的最大长度，超过则丢弃
  endpoints:
    - name: "hitokoto.cn"
      url: "https://v1.hitokoto.cn/"
      parser:
        mappings:
          text: "/hitokoto"
          author: "from"

    - name: "api.xygeng.cn"
      url: "https://api.xygeng.cn/one"
      parser:
        mappings:
          text: "/data/content"
          author: "/data/name"

    - name: "uapis.cn"
      url: "https://uapis.cn/api/say"
      parser:
        type: "plain_text"

    - name: "oddfar.com"
      url: "https://api.oddfar.com/yl/q.php"
      parser:
        type: "plain_text"

    - name: "iamwawa.cn-lizhi"
      url: "https://www.iamwawa.cn/home/lizhi/ajax"
      headers:
        Referer: "https://www.iamwawa.cn/home/lizhi"
        X-Requested-With: "XMLHttpRequest"
      parser:
        mappings:
          text: "data"

    - name: "aa1.cn-wenan"
      url: "http://zj.v.api.aa1.cn/api/wenan-wm/?type=json"
      parser:
        mappings:
          text: "msg"

    - name: "wudada.online"
      url: "http://www.wudada.online/Api/MrYy"
      parser:
        mappings:
          text: "/data/hitokoto"
          author: "/data/from"

    - name: "mu-jie.cc-stray-birds"
      url: "https://api.mu-jie.cc/stray-birds/range?type=json"
      parser:
        mappings:
          text: "cn"

    - name: "apihz.cn"
      url: "https://cn.apihz.cn/api/yiyan/api.php?id=88888888&key=88888888"
      parser:
        mappings:
          text: "msg"

    - name: "aa1.cn-pyq"
      url: "https://v.api.aa1.cn/api/pyq/index.php?aa1=json"
      parser:
        mappings:
          text: "pyq"

    - name: "iamwawa.cn-shici"
      url: "https://www.iamwawa.cn/home/shici/ajax"
      headers:
        Referer: "https://www.iamwawa.cn/home/shici"
        X-Requested-With: "XMLHttpRequest"
      parser:
        mappings:
          text: "/data/content"
          author: "/data/author"

    - name: "nnxv.cn"
      url: "https://api.nnxv.cn/api/yiyan.php"
      parser:
        mappings:
          text: "content"
          author: "from"

    - name: "jinrishici.com"
      url: "https://v1.jinrishici.com/all"
      parser:
        mappings:
          text: "content"
          author: "author"

    - name: "dwo.cc"
      url: "https://api.dwo.cc/api/yi?api=yan"
      parser:
        type: "plain_text"

    - name: "api-m.com-renjian"
      url: "https://v2.api-m.com/api/renjian"
      parser:
        mappings:
          text: "data"

    - name: "api-m.com-hitokoto"
      url: "https://v2.api-m.com/api/yiyan?type=hitokoto"
      parser:
        mappings:
          text: "data"

    - name: "api-m.com-poetry"
      url: "https://v2.api-m.com/api/yiyan?type=poetry"
      parser:
        mappings:
          text: "data"

    - name: "hhlqilongzhu.cn"
      url: "https://www.hhlqilongzhu.cn/api/yiyan.php"
      parser:
        type: "plain_text"

